[package]
name = "redbpf"
version = "0.1.0"
authors = ["Peter Parkanyi <peter@redsift.io>"]
edition = '2018'

[dependencies]
bpf-sys = { path = "../bpf-sys" }
goblin = "^0.0.15"
zero = "0.1"
libc = "0.2"
bindgen = "0.37"
regex = "1.0"
lazy_static = "1.0"